version: "3"
services:
  wordpress:                                                                                               
    image: wordpress:5.6.0-php7.3-fpm-alpine                                                              
    container_name: wordpress                                                                              
    restart: unless-stopped                                                                                
    environment:                                                                                          
      WORDPRESS_DB_HOST: db:3306                                                                           
      WORDPRESS_DB_USER: ${WORDPRESS_USER}                                                                 
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_PASSWORD}                                                         
      WORDPRESS_DB_NAME: ${WORDPRESS_DB}                                                                   
    depends_on:                                                                                       
      - "db"                                                                                            
    volumes:                                                                                           
      - ./wordpress:/var/www/html

        #  nginx:
        #    image: nginx:latest
        #    container_name: nginx
        #    restart: unless-stopped
        #    ports:
        #      - "80:80"
        #      - "443:443"
        #    volumes:
        #        - ./nginx:/etc/nginx/conf.d
        #        - ./logs/nginx:/var/log/nginx
        #        - ./react-app/build/:/var/www/roboconcrce.org
        #        - ./wordpress:/var/www/html
        #        - ./certs:/etc/certs:ro

  swag:
    image: ghcr.io/linuxserver/swag:version-1.18.0
    container_name: swag
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC 
      - URL=roboconcrce.org
      - SUBDOMAINS=www,blog,
      - VALIDATION=http
      - ONLY_SUBDOMAINS=false #optional
    volumes:
      - ./swag-config:/config
      - ./react-app/build/:/var/www/roboconcrce.org
      - ./wordpress:/var/www/html
    ports:
      - 443:443
      - 80:80 
    restart: unless-stopped

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: unless-stopped
    hostname: roboconcrce.org
    ports:
      - 3333:80
    environment:
      PMA_HOST: db
      PMA_ABSOLUTE_URI: "https://phpmyadmin.roboconcrce.org/"
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}

  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE:  ${WORDPRESS_DB}
      MYSQL_USER: ${WORDPRESS_USER}
      MYSQL_PASSWORD: ${WORDPRESS_PASSWORD}

volumes:
  db_data: {}
